# Generated by Django 3.2.25 on 2024-04-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_notifaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
